version: "3.9"

services:

  mongo1:
    build:
      context: ./docker
    image: mongocustom
    container_name: mongo1
    hostname: mongo1
    networks: [mongonet]
    ports:
      - "27017:27017"

    volumes:
      - mongo1-data:/data/db
      - mongo1-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo2:
    image: mongocustom
    container_name: mongo2
    hostname: mongo2
    networks: [mongonet]
    volumes:
      - mongo2-data:/data/db
      - mongo2-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20

  mongo3:
    image: mongocustom
    container_name: mongo3
    hostname: mongo3
    networks: [mongonet]
    volumes:
      - mongo3-data:/data/db
      - mongo3-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    command: --config /etc/mongod.conf
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 20


  redis:
    image: redis:latest
    container_name: redis-cache
    hostname: redis
    networks: [mongonet]
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  init-replica:
    image: mongo:8.0.1
    container_name: init-replica
    networks: [mongonet]
    depends_on:
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
      mongo3:
        condition: service_healthy
    command: >
      bash -ec "
        echo 'Waiting for mongo1:27017...';
        for i in {1..60}; do
          (echo > /dev/tcp/mongo1/27017) >/dev/null 2>&1 && break;
          sleep 1;
        done

        echo 'Initializing replica set...';
        mongosh --host mongo1:27017 -u admin -p adminpassword --authenticationDatabase admin --eval '
          rs.initiate({
            _id: \"rs0\",
            members: [
              { _id: 0, host: \"mongo1:27017\" },
              { _id: 1, host: \"mongo2:27017\" },
              { _id: 2, host: \"mongo3:27017\" }
            ]
          })
        ';
        echo 'Replica set initialization DONE.';
      "

  test-runner:
    image: maven:3.9.6-eclipse-temurin-21
    container_name: test-runner
    networks: [mongonet]
    depends_on:
      init-replica:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: [ "mvn", "test" ]

  kafka1:
    image: apache/kafka:4.1.1
    container_name: kafka1
    hostname: kafka1
    ports:
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # wewnatrz dockera: kafka1:9092
      # host: localhost:29092
      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks: [ mongonet ]

  kafka2:
    image: apache/kafka:4.1.1
    container_name: kafka2
    hostname: kafka2
    ports:
      - "39092:29092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://localhost:39092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka1
    networks: [ mongonet ]

  kafka3:
    image: apache/kafka:4.1.1
    container_name: kafka3
    hostname: kafka3
    ports:
      - "49092:29092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka3:9092,PLAINTEXT_HOST://localhost:49092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    depends_on:
      - kafka1
    networks: [ mongonet ]

  init-kafka-topic:
    image: apache/kafka:4.1.1
    container_name: init-kafka-topic
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    restart: "no"
    entrypoint: [ "/bin/bash", "-lc" ]
    command: >
      echo "Waiting for Kafka to be ready...";
      for i in $$(seq 1 60); do
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --list >/dev/null 2>&1 && echo "Kafka ready" && break;
        echo "Kafka not ready yet ($$i/60)...";
        sleep 2;
      done;
      echo "Creating topic wypozyczenia-rezerwacje (3 partitions, RF=3)...";
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --create --if-not-exists --topic wypozyczenia-rezerwacje --partitions 3 --replication-factor 3;
      echo "Topic describe:";
      /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka1:9092,kafka2:9092,kafka3:9092 --describe --topic wypozyczenia-rezerwacje;
      echo "DONE";
    networks: [ mongonet ]

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
    networks: [ mongonet ]


  rental-consumer:
    image: maven:3.9.9-eclipse-temurin-21
    deploy:
      mode: replicated
      replicas: 2
    working_dir: /app
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_TOPIC: "wypozyczenia-rezerwacje"
      MONGO_URI: "mongodb://admin:adminpassword@mongo1:27017/?authSource=admin&replicaSet=rs0"
      MONGO_DB: "library_analytics_db"
    entrypoint: [ "mvn" ]
    command:
      - "-q"
      - "-DskipTests"
      - "exec:java@run-kafka-consumer"
      - "-Dexec.args=consumer-group-1"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks: [ mongonet ]

  demo-producer:
    image: maven:3.9.9-eclipse-temurin-21
    container_name: demo-producer
    working_dir: /app
    volumes:
      - .:/app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka1:9092,kafka2:9092,kafka3:9092"
      KAFKA_RENTAL_TOPIC: "wypozyczenia-rezerwacje"
      MONGO_URI: "mongodb://admin:adminpassword@mongo1:27017,mongo2:27017,mongo3:27017/?authSource=admin&replicaSet=rs0"
      MONGO_DB: "library_demo_db"
    entrypoint: [ "mvn" ]
    command:
      - "-q"
      - "-DskipTests"
      - "exec:java@run-app"
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks: [ mongonet ]
    restart: "no"



volumes:
  mongo1-data:
  mongo1-config:
  mongo2-data:
  mongo2-config:
  mongo3-data:
  mongo3-config:


networks:
  mongonet:
    name: nbd_mongonet